<?php

namespace App\Http\Controllers;

use App\Models\ActivityLog;
use App\Models\Beneficiary;
use App\Support\ActivityLogger;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\View\View;

class QrScannerController extends Controller
{
    public function index(): View
    {
        return view('qr-scanner.index', [
            'recentScans' => ActivityLog::query()
                ->with(['user', 'subject'])
                ->whereIn('action', [
                    'beneficiary.qr_scan_verified',
                    'beneficiary.qr_scan_rejected',
                ])
                ->latest()
                ->paginate(2, ['*'], 'history_page')
                ->withQueryString(),
        ]);
    }

    public function verify(Request $request, ActivityLogger $activityLogger): JsonResponse
    {
        $validated = $request->validate([
            'payload' => ['required', 'string', 'max:2048'],
        ]);

        [$token, $reason] = $this->extractVerificationToken($validated['payload']);

        if ($token === null) {
            $activityLogger->log(
                'beneficiary.qr_scan_rejected',
                'Rejected a QR scan because it did not match a system-generated beneficiary verification code.',
                null,
                [
                    'payload' => $validated['payload'],
                    'reason' => $reason,
                    'result' => 'invalid',
                ],
            );

            return response()->json([
                'is_legitimate' => false,
                'reason' => 'not_system_generated',
                'message' => 'The scanned QR code is not a system-generated beneficiary code.',
                'details' => 'Scan only QR codes generated by this beneficiary system.',
                'notice_title' => 'Warning: Not a legitimate beneficiary QR code.',
                'notice' => 'This scanned code was not generated by the system and must not be treated as a legitimate beneficiary verification QR code.',
            ], 422);
        }

        $beneficiary = Beneficiary::query()->where('qr_token', $token)->first();

        if ($beneficiary === null) {
            $activityLogger->log(
                'beneficiary.qr_scan_rejected',
                'Rejected a beneficiary QR scan because the token was not found in the system.',
                null,
                [
                    'payload' => $validated['payload'],
                    'token' => $token,
                    'reason' => 'token_not_found',
                    'result' => 'invalid',
                ],
            );

            return response()->json([
                'is_legitimate' => false,
                'reason' => 'token_not_found',
                'message' => 'This QR code is not registered in the beneficiary system.',
                'details' => 'The code format matches the system pattern, but no beneficiary record was found.',
                'notice_title' => 'Warning: QR code is not legitimate.',
                'notice' => 'The scanned code follows the system route format, but its verification token is not registered to any beneficiary in this system.',
            ], 422);
        }

        $activityLogger->log(
            'beneficiary.qr_scan_verified',
            "Verified beneficiary {$beneficiary->full_name} using the admin QR scanner.",
            $beneficiary,
            [
                'payload' => $validated['payload'],
                'beneficiary_number' => $beneficiary->beneficiary_number,
                'status' => $beneficiary->status,
                'result' => 'verified',
            ],
        );

        return response()->json([
            'is_legitimate' => true,
            'message' => 'Legitimate beneficiary code verified.',
            'beneficiary' => [
                'full_name' => $beneficiary->full_name,
                'beneficiary_number' => $beneficiary->beneficiary_number,
                'barangay' => $beneficiary->barangay,
                'category' => $beneficiary->category,
                'status' => $beneficiary->status,
                'photo_url' => $beneficiary->photo_path ? Storage::url($beneficiary->photo_path) : null,
            ],
        ]);
    }

    /**
     * @return array{0:?string,1:string}
     */
    private function extractVerificationToken(string $payload): array
    {
        $path = parse_url(trim($payload), PHP_URL_PATH);

        if (! is_string($path) || $path === '') {
            return [null, 'invalid_path'];
        }

        $normalizedPath = trim($path, '/');

        if (! preg_match('~^verification/([^/?#]+)$~', $normalizedPath, $matches)) {
            return [null, 'invalid_verification_route'];
        }

        return [$matches[1], 'ok'];
    }
}
