<x-app-layout>
    <x-slot name="header">
        <div>
            <p class="eyebrow">Legitimacy Check</p>
            <h1 class="page-title">Beneficiary QR Scanner</h1>
        </div>
    </x-slot>

    <section class="page-shell space-y-6">
        <div class="detail-grid qr-scanner-layout">
            <article class="panel-card scanner-main-card" x-data="beneficiaryQrScanner({ verifyUrl: @js(route('qr-scanner.verify')) })" x-on:keydown.escape.window="resultModalOpen && closeResultModal()">
                <div class="section-heading">
                    <div>
                        <h2 class="section-title">Live scanner</h2>
                        <p class="section-copy mt-2">Point the camera at a beneficiary QR code generated by this system. Non-system QR codes are flagged immediately as not legitimate.</p>
                    </div>
                </div>

                <div class="scanner-shell">
                    <div class="scanner-preview">
                        <video x-ref="video" class="scanner-preview__video" playsinline muted></video>
                        <div class="scanner-preview__overlay"></div>
                        <div class="scanner-preview__frame"></div>

                        <div class="scanner-preview__empty" x-show="!scanning && !processing" x-cloak>
                            <p class="eyebrow text-white/90">Scanner Ready</p>
                            <p class="mt-2 text-sm leading-6 text-white/80">Start the camera and align the QR code inside the square frame.</p>
                        </div>

                        <div class="scanner-preview__state" x-show="processing" x-cloak>
                            Verifying scanned code...
                        </div>
                    </div>

                    <div class="flex flex-col gap-2 sm:flex-row sm:flex-wrap">
                        <button class="button-primary" type="button" x-show="!scanning" @click="start()" :disabled="starting || processing">
                            <span x-show="!starting">Start Scanner</span>
                            <span x-show="starting" x-cloak>Opening Camera...</span>
                        </button>

                        <button class="button-secondary" type="button" x-show="scanning" x-cloak @click="stop()">Stop Scanner</button>
                        <button class="button-secondary" type="button" x-show="result && !resultModalOpen" x-cloak @click="scanAgain()">Scan Another Code</button>
                    </div>

                    <p class="section-copy">Every valid or rejected scan is saved in the system. Legitimate results identify the beneficiary record that owns the generated QR code.</p>

                    <div class="note-block border-rose-200 bg-rose-50/90 text-rose-700" x-show="error" x-text="error" x-cloak></div>
                </div>

                <template x-teleport="body">
                    <div class="scanner-result-modal" x-show="result && resultModalOpen" x-cloak>
                        <div class="scanner-result-modal__backdrop" @click="closeResultModal()"></div>

                        <div class="scanner-result-modal__panel" role="dialog" aria-modal="true" aria-labelledby="qr-scanner-result-title" @click.stop>
                            <div class="scanner-result-modal__header">
                                <div>
                                    <span x-bind:class="result?.is_legitimate ? 'scanner-result-modal__status scanner-result-modal__status--verified' : 'scanner-result-modal__status scanner-result-modal__status--warning'" x-text="result?.is_legitimate ? 'Legitimate Code' : 'Not Legitimate'"></span>
                                    <h3 class="scanner-result-modal__title" id="qr-scanner-result-title" x-text="result?.message"></h3>
                                    <p class="scanner-result-modal__subtitle" x-text="result?.is_legitimate ? 'This beneficiary QR code is legitimate and linked to a registered record in the system.' : 'This scanned QR code is not legitimate and must not be used for beneficiary verification.'"></p>
                                </div>

                                <button class="scanner-result-modal__close" type="button" @click="closeResultModal()">Close</button>
                            </div>

                            <div class="scanner-result-modal__body">
                                <template x-if="result?.is_legitimate">
                                    <div class="scanner-result-modal__verified-grid">
                                        <div class="scanner-result-modal__photo">
                                            <template x-if="result?.beneficiary?.photo_url">
                                                <img :src="result?.beneficiary?.photo_url" :alt="`${result?.beneficiary?.full_name} photo`">
                                            </template>

                                            <template x-if="!result?.beneficiary?.photo_url">
                                                <div class="scanner-result-modal__photo-fallback">
                                                    <strong>No photo uploaded</strong>
                                                    <p>The beneficiary record is valid, but no image is saved for this profile yet.</p>
                                                </div>
                                            </template>
                                        </div>

                                        <div class="scanner-result-modal__content">
                                            <div class="scanner-result-modal__card">
                                                <p class="scanner-result-modal__card-label">Verified beneficiary details</p>

                                                <dl class="detail-list mt-4">
                                                    <div>
                                                        <dt>Beneficiary ID</dt>
                                                        <dd x-text="result?.beneficiary?.beneficiary_number"></dd>
                                                    </div>
                                                    <div>
                                                        <dt>Full Name</dt>
                                                        <dd x-text="result?.beneficiary?.full_name"></dd>
                                                    </div>
                                                    <div>
                                                        <dt>Barangay</dt>
                                                        <dd x-text="result?.beneficiary?.barangay"></dd>
                                                    </div>
                                                    <div>
                                                        <dt>Category</dt>
                                                        <dd x-text="result?.beneficiary?.category"></dd>
                                                    </div>
                                                    <div>
                                                        <dt>Record Status</dt>
                                                        <dd x-text="result?.beneficiary?.status"></dd>
                                                    </div>
                                                </dl>
                                            </div>

                                            <div class="scanner-result-modal__card">
                                                <p class="scanner-result-modal__card-label">Scanned payload</p>
                                                <p class="scanner-result-modal__payload" x-text="result?.payload"></p>
                                            </div>
                                        </div>
                                    </div>
                                </template>

                                <template x-if="!result?.is_legitimate">
                                    <div class="scanner-result-modal__content">
                                        <div class="scanner-result__notice">
                                            <p class="scanner-result__notice-title" x-text="result?.notice_title"></p>
                                            <p class="scanner-result__notice-copy" x-text="result?.notice"></p>
                                        </div>

                                        <div class="scanner-result-modal__card">
                                            <p class="scanner-result-modal__card-label">Rejection details</p>
                                            <p class="scanner-result__details" x-text="result?.details"></p>
                                        </div>

                                        <div class="scanner-result-modal__card">
                                            <p class="scanner-result-modal__card-label">Scanned payload</p>
                                            <p class="scanner-result-modal__payload" x-text="result?.payload"></p>
                                        </div>
                                    </div>
                                </template>
                            </div>

                            <div class="scanner-result-modal__footer">
                                <button class="button-secondary" type="button" @click="closeResultModal()">Close</button>
                                <button class="button-primary" type="button" @click="scanAgain()">Scan Another Code</button>
                            </div>
                        </div>
                    </div>
                </template>
            </article>

            <aside class="scanner-sidebar space-y-6">
                <article class="panel-card">
                    <h2 class="section-title">How it works</h2>
                    <ul class="insight-list mt-4">
                        <li><span>Accepted format</span><strong>System QR only</strong></li>
                        <li><span>Verification source</span><strong>Beneficiary QR token</strong></li>
                        <li><span>Audit trail</span><strong>Every scan saved</strong></li>
                    </ul>
                </article>

                <article class="panel-card scanner-history-card">
                    <h2 class="section-title">Recent scan history</h2>
                    <ul class="timeline-list scanner-history-list mt-4">
                        @forelse ($recentScans as $scan)
                            <li>
                                <div class="timeline-meta">{{ $scan->created_at->format('M d, Y h:i A') }} · {{ $scan->user?->name ?? 'System' }}</div>
                                <div class="mt-2 flex flex-col gap-3">
                                    <div class="flex flex-col gap-3 md:flex-row md:items-start md:justify-between">
                                        <div class="timeline-copy">{{ $scan->description }}</div>
                                        <span @class([
                                            'status-chip',
                                            'status-chip--active' => $scan->action === 'beneficiary.qr_scan_verified',
                                            'status-chip--inactive' => $scan->action === 'beneficiary.qr_scan_rejected',
                                        ])>
                                            {{ $scan->action === 'beneficiary.qr_scan_verified' ? 'Verified' : 'Rejected' }}
                                        </span>
                                    </div>

                                    @if ($scan->subject)
                                        <div class="text-sm text-slate-600">
                                            {{ $scan->subject->full_name }} · {{ $scan->properties['beneficiary_number'] ?? 'No ID recorded' }}
                                        </div>
                                    @elseif (! empty($scan->properties['reason']))
                                        <div class="text-sm text-slate-600">
                                            Reason: {{ ucfirst(str_replace('_', ' ', $scan->properties['reason'])) }}
                                        </div>
                                    @endif
                                </div>
                            </li>
                        @empty
                            <li class="timeline-copy">No QR scans recorded yet.</li>
                        @endforelse
                    </ul>

                    @if ($recentScans->hasPages())
                        <div class="scanner-history-pagination">
                            @if ($recentScans->onFirstPage())
                                <span class="scanner-history-pagination__link scanner-history-pagination__link--disabled">Previous</span>
                            @else
                                <a class="scanner-history-pagination__link" href="{{ $recentScans->previousPageUrl() }}">Previous</a>
                            @endif

                            <p class="scanner-history-pagination__meta">
                                Page {{ $recentScans->currentPage() }} of {{ $recentScans->lastPage() }}
                            </p>

                            @if ($recentScans->hasMorePages())
                                <a class="scanner-history-pagination__link" href="{{ $recentScans->nextPageUrl() }}">Next</a>
                            @else
                                <span class="scanner-history-pagination__link scanner-history-pagination__link--disabled">Next</span>
                            @endif
                        </div>
                    @endif
                </article>
            </aside>
        </div>
    </section>
</x-app-layout>
